#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 154)

	def initialize(tokens)
		@tokens = tokens
	end
...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    19,    20,    18,    19,    20,    18,    19,    20,    18,    19,
    20,    18,    19,    20,    18,    19,    20,    18,     7,     8,
     9,     7,     8,     9,    19,    20,    18,    27,    23,   101,
    22,    23,    21,    22,    23,    21,    22,    23,    21,    22,
    23,    21,    22,    23,    21,    22,   102,    21,    19,    20,
    18,    37,    23,    37,    22,    42,    21,    19,    20,    18,
    19,    20,    18,     7,     8,     9,    37,    38,    42,    38,
    37,    43,    80,    78,    79,    37,    23,   120,    22,    37,
    21,   103,    38,    27,    43,    23,    38,    22,    23,    21,
    22,    38,    21,    39,    40,    38,    39,    40,    37,    41,
    46,    37,    41,    42,   104,    83,    42,    39,    40,    65,
    39,    40,    64,    41,    38,    37,    41,    38,    84,    43,
    42,   124,    43,    39,    40,   105,    86,    27,    37,    41,
   125,    38,    27,    42,    27,   117,    43,    39,    40,    27,
    39,    40,    37,    41,    38,    37,    41,    42,   106,    43,
    42,    39,    40,   107,    39,    40,    26,    41,    38,    37,
    41,    38,    27,    43,    42,   116,    43,    88,    76,    77,
   128,   108,   115,    27,    27,    38,    73,    72,    27,    70,
    43,    66,    67,    68,    69,    59,    57,    61,    58,    56,
    60,    63,    62,    75,    74,   109,   100,    99,    81,    71,
    82,    85,    29,   118,   119,    87,    31,    30,    29,    25,
    24,   126,     3,     2 ]

racc_action_check = [
    82,    82,    82,   126,   126,   126,     2,     2,     2,    83,
    83,    83,    87,    87,    87,    27,    27,    27,    28,    28,
    28,     2,     2,     2,   118,   118,   118,    52,    82,    68,
    82,   126,    82,   126,     2,   126,     2,    83,     2,    83,
    87,    83,    87,    27,    87,    27,    69,    27,    23,    23,
    23,    59,   118,    58,   118,    65,   118,   116,   116,   116,
    25,    25,    25,    23,    23,    23,    56,    59,    64,    58,
    57,    65,    42,    42,    42,    60,    23,   114,    23,    61,
    23,    70,    56,   114,    64,   116,    57,   116,    25,   116,
    25,    60,    25,    21,    21,    61,    22,    22,    21,    21,
    22,    22,    22,    21,    72,    45,    22,    63,    63,    36,
    20,    20,    36,    63,    21,    20,    20,    22,    45,    21,
    20,   121,    22,   119,   119,    73,    47,   121,   119,   119,
   122,    20,    47,   119,   122,   111,    20,    84,    84,   111,
    85,    85,    84,    84,   119,    85,    85,    84,    74,   119,
    85,    62,    62,    75,    30,    30,     5,    62,    84,    30,
    30,    85,     5,    84,    30,   110,    85,    50,    41,    41,
   127,    78,   110,    50,   127,    30,    39,    39,   110,    37,
    30,    37,    37,    37,    37,    33,    33,    33,    33,    33,
    33,    34,    34,    40,    40,    79,    67,    66,    43,    38,
    44,    46,    29,   112,   113,    48,    19,    18,     6,     4,
     3,   123,     1,     0 ]

racc_action_pointer = [
   181,   212,     2,   210,   182,   123,   202,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   189,   200,
   108,    91,    94,    44,   nil,    56,   nil,    11,    -1,   196,
   152,   nil,   nil,   172,   182,   nil,    94,   159,   192,   167,
   184,   166,    43,   186,   162,    78,   175,    93,   178,   nil,
   134,   nil,   -12,   nil,   nil,   nil,    59,    63,    46,    44,
    68,    72,   149,   105,    56,    43,   190,   189,    22,    39,
    74,   nil,   101,   122,   146,   151,   nil,   nil,   159,   183,
   nil,   nil,    -4,     5,   135,   138,   nil,     8,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   139,   100,   176,   164,    44,   nil,    53,   nil,    20,   121,
   nil,    88,    95,   184,   nil,   nil,    -1,   135,   nil ]

racc_action_default = [
   -61,   -61,   -61,   -61,   -61,   -61,   -61,    -5,    -6,    -7,
   -10,   -11,   -12,   -13,   -14,   -15,   -16,   -17,   -61,   -61,
   -61,   -61,   -61,   -61,   129,   -61,    -2,   -61,    -4,    -9,
   -61,   -21,   -22,   -31,   -32,   -33,   -34,   -61,   -61,   -61,
   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -30,
   -61,   -11,   -20,    -3,    -8,   -18,   -61,   -61,   -61,   -61,
   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -61,   -61,
   -61,   -40,   -61,   -61,   -61,   -61,   -45,   -46,   -61,   -61,
   -60,   -59,   -61,   -61,   -61,   -61,   -29,   -61,    -1,   -47,
   -48,   -49,   -50,   -51,   -52,   -53,   -54,   -55,   -56,   -35,
   -36,   -37,   -38,   -39,   -41,   -43,   -42,   -44,   -57,   -58,
   -61,   -61,   -61,   -61,   -61,   -23,   -61,   -25,   -61,   -61,
   -28,   -61,   -61,   -61,   -24,   -26,   -61,   -61,   -27 ]

racc_goto_table = [
     5,    32,    44,    45,    28,     4,    95,    96,    97,    98,
    48,    55,    89,    90,    91,    92,    93,    94,    51,     1,
   nil,    47,   nil,    50,   nil,    52,    49,    54,   nil,   nil,
   nil,    53,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   112,   113,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   110,   111,   nil,   nil,   nil,   114,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   123,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   121,   nil,   122,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   127 ]

racc_goto_check = [
     3,    14,    14,    14,     5,     2,    17,    17,    19,    19,
    15,    14,    16,    16,    16,    16,    16,    16,     7,     1,
   nil,     3,   nil,     3,   nil,     3,     2,     5,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    14,    14,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,     3,   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    14,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,    19,     3,    -2,   nil,    -2,   nil,    -9,   nil,   nil,
   nil,   nil,   nil,   nil,   -19,   -13,   -44,   -56,   nil,   -56 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     6,   nil,    10,    11,    12,    13,
    14,    15,    16,    17,   nil,   nil,    33,    34,    35,    36 ]

racc_reduce_table = [
  0, 0, :racc_error,
  5, 42, :_reduce_1,
  3, 42, :_reduce_none,
  3, 43, :_reduce_3,
  2, 43, :_reduce_4,
  1, 45, :_reduce_5,
  1, 45, :_reduce_6,
  1, 45, :_reduce_7,
  2, 46, :_reduce_8,
  1, 46, :_reduce_9,
  1, 44, :_reduce_10,
  1, 44, :_reduce_11,
  1, 44, :_reduce_12,
  1, 44, :_reduce_13,
  1, 44, :_reduce_14,
  1, 44, :_reduce_15,
  1, 44, :_reduce_16,
  1, 44, :_reduce_17,
  3, 47, :_reduce_18,
  3, 48, :_reduce_19,
  1, 48, :_reduce_none,
  2, 49, :_reduce_21,
  2, 50, :_reduce_22,
  5, 51, :_reduce_23,
  7, 51, :_reduce_24,
  5, 52, :_reduce_25,
  7, 53, :_reduce_26,
  9, 53, :_reduce_27,
  5, 54, :_reduce_28,
  3, 54, :_reduce_29,
  1, 56, :_reduce_30,
  1, 55, :_reduce_31,
  1, 55, :_reduce_32,
  1, 55, :_reduce_33,
  1, 55, :_reduce_34,
  3, 57, :_reduce_35,
  3, 57, :_reduce_36,
  3, 57, :_reduce_37,
  3, 57, :_reduce_38,
  3, 57, :_reduce_39,
  2, 57, :_reduce_40,
  3, 58, :_reduce_41,
  3, 58, :_reduce_42,
  3, 58, :_reduce_43,
  3, 58, :_reduce_44,
  2, 58, :_reduce_45,
  2, 58, :_reduce_46,
  3, 59, :_reduce_47,
  3, 59, :_reduce_48,
  3, 59, :_reduce_49,
  3, 59, :_reduce_50,
  3, 59, :_reduce_51,
  3, 59, :_reduce_52,
  3, 59, :_reduce_53,
  3, 59, :_reduce_54,
  3, 59, :_reduce_55,
  3, 59, :_reduce_56,
  3, 60, :_reduce_57,
  3, 60, :_reduce_58,
  2, 60, :_reduce_59,
  2, 60, :_reduce_60 ]

racc_reduce_n = 61

racc_shift_n = 129

racc_token_table = {
  false => 0,
  :error => 1,
  :TRUE => 2,
  :FALSE => 3,
  :READ => 4,
  :WRITE => 5,
  :IDENTIFIER => 6,
  :NUMBER => 7,
  :NOT => 8,
  :OR => 9,
  :AND => 10,
  :EMPTY_CANVAS => 11,
  :CANVAS => 12,
  :MORE_EQUAL => 13,
  :LESS_EQUAL => 14,
  :INEQUAL => 15,
  :MORE => 16,
  :LESS => 17,
  :EQUAL => 18,
  :EXCLAMATION_MARK => 19,
  :PERCENT => 20,
  :AT => 21,
  :PLUS => 22,
  :MINUS => 23,
  :TIMES => 24,
  :OBELUS => 25,
  :COLON => 26,
  :PIPE => 27,
  :DOLLAR => 28,
  :APOSTROPHE => 29,
  :AMPERSAND => 30,
  :VIRGUILE => 31,
  :LCURLY => 32,
  :RCURLY => 33,
  :LBRACKET => 34,
  :RBRACKET => 35,
  :LPARENTHESIS => 36,
  :RPARENTHESIS => 37,
  :INTERROGATION_MARK => 38,
  :SEMI_COLON => 39,
  :DOUBLE_DOT => 40 }

racc_nt_base = 41

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "TRUE",
  "FALSE",
  "READ",
  "WRITE",
  "IDENTIFIER",
  "NUMBER",
  "NOT",
  "OR",
  "AND",
  "EMPTY_CANVAS",
  "CANVAS",
  "MORE_EQUAL",
  "LESS_EQUAL",
  "INEQUAL",
  "MORE",
  "LESS",
  "EQUAL",
  "EXCLAMATION_MARK",
  "PERCENT",
  "AT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OBELUS",
  "COLON",
  "PIPE",
  "DOLLAR",
  "APOSTROPHE",
  "AMPERSAND",
  "VIRGUILE",
  "LCURLY",
  "RCURLY",
  "LBRACKET",
  "RBRACKET",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "INTERROGATION_MARK",
  "SEMI_COLON",
  "DOUBLE_DOT",
  "$start",
  "ESTRUC",
  "DEC",
  "INSTR",
  "TIPO",
  "LISTIDENT",
  "ASSIGN",
  "SEC",
  "ENTR",
  "SAL",
  "CONDIC",
  "ITERIND",
  "ITERDET",
  "INCOR",
  "EXPR",
  "LISTADEC",
  "EXPRARIT",
  "EXPRBOOL",
  "EXPRRELAC",
  "EXPRLIENZ" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 15)
  def _reduce_1(val, _values, result)
     result = 
    result
  end
.,.,

# reduce 2 omitted

module_eval(<<'.,.,', 'Parser.y', 22)
  def _reduce_3(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 23)
  def _reduce_4(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 28)
  def _reduce_5(val, _values, result)
    result =
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 29)
  def _reduce_6(val, _values, result)
    result =
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 30)
  def _reduce_7(val, _values, result)
    result =
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 35)
  def _reduce_8(val, _values, result)
    result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 36)
  def _reduce_9(val, _values, result)
    result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 41)
  def _reduce_10(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 42)
  def _reduce_11(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 43)
  def _reduce_12(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 44)
  def _reduce_13(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 45)
  def _reduce_14(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 46)
  def _reduce_15(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 47)
  def _reduce_16(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 48)
  def _reduce_17(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 53)
  def _reduce_18(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 58)
  def _reduce_19(val, _values, result)
     result = 
    result
  end
.,.,

# reduce 20 omitted

module_eval(<<'.,.,', 'Parser.y', 64)
  def _reduce_21(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 69)
  def _reduce_22(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 74)
  def _reduce_23(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 75)
  def _reduce_24(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 80)
  def _reduce_25(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 85)
  def _reduce_26(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 86)
  def _reduce_27(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 91)
  def _reduce_28(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 92)
  def _reduce_29(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 97)
  def _reduce_30(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 102)
  def _reduce_31(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 103)
  def _reduce_32(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 104)
  def _reduce_33(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 105)
  def _reduce_34(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 110)
  def _reduce_35(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 111)
  def _reduce_36(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 112)
  def _reduce_37(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 113)
  def _reduce_38(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 114)
  def _reduce_39(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 115)
  def _reduce_40(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 120)
  def _reduce_41(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 121)
  def _reduce_42(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 122)
  def _reduce_43(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 123)
  def _reduce_44(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 124)
  def _reduce_45(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 125)
  def _reduce_46(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 130)
  def _reduce_47(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 131)
  def _reduce_48(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 132)
  def _reduce_49(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 133)
  def _reduce_50(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 134)
  def _reduce_51(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 135)
  def _reduce_52(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 136)
  def _reduce_53(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 137)
  def _reduce_54(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 138)
  def _reduce_55(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 139)
  def _reduce_56(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 144)
  def _reduce_57(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 145)
  def _reduce_58(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 146)
  def _reduce_59(val, _values, result)
     result = 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 147)
  def _reduce_60(val, _values, result)
     result = 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
