#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'
class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 163)

require "./Clases.rb"

	def initialize(tokens)
		@tokens = tokens
	end

	def parser
		do_parse
	end

	def next_token
		@tokens.next_token
	end
...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    28,    28,    28,   101,    28,    28,    28,    25,    11,    28,
    78,     9,    57,    58,    59,    55,    56,    66,    65,    67,
    68,    69,    70,    31,    60,    61,    64,    11,    63,    62,
     9,    57,    58,    59,    11,     8,    10,    79,    24,   108,
   100,   112,   109,   102,    27,    95,     4,    11,    20,    21,
    11,    11,    35,     3,     8,    10,     3,   nil,    23,    37,
    22,   nil,   nil,    38,   nil,   nil,    44,    45,    35,   nil,
    11,    43,   nil,    46,   nil,    37,    57,    58,    59,    38,
    36,   nil,    44,    45,    35,   nil,    11,    43,   nil,    46,
   nil,    37,   nil,   nil,   nil,    38,    36,   nil,    44,    45,
    35,   nil,    11,    43,   nil,    46,   nil,    37,   nil,   nil,
   nil,    38,    36,   nil,    44,    45,    35,   nil,    11,    43,
   nil,    46,   nil,    37,   nil,   nil,   nil,    38,    36,   nil,
    44,    45,    35,   nil,    11,    43,   nil,    46,   nil,    37,
   nil,   nil,   nil,    38,    36,   nil,    44,    45,    35,   nil,
    11,    43,   nil,    46,   nil,    37,   nil,   nil,   nil,    38,
    36,   nil,    44,    45,    35,   nil,    11,    43,   nil,    46,
   nil,    37,   nil,   nil,   nil,    38,    36,   nil,    44,    45,
    35,   nil,    11,    43,   nil,    46,   nil,    37,   nil,   nil,
   nil,    38,    36,   nil,    44,    45,    35,   nil,    11,    43,
   nil,    46,   nil,    37,   nil,   nil,   nil,    38,    36,   nil,
    44,    45,    35,   nil,    11,    43,   nil,    46,   nil,    37,
   nil,   nil,   nil,    38,    36,   nil,    44,    45,    35,   nil,
    11,    43,   nil,    46,   nil,    37,   nil,   nil,   nil,    38,
    36,   nil,    44,    45,    35,   nil,    11,    43,   nil,    46,
   nil,    37,   nil,   nil,   nil,    38,    36,   nil,    44,    45,
    35,   nil,    11,    43,   nil,    46,   nil,    37,   nil,   nil,
   nil,    38,    36,   nil,    44,    45,    35,   nil,    11,    43,
   nil,    46,   nil,    37,   nil,   nil,   nil,    38,    36,   nil,
    44,    45,    35,   nil,    11,    43,   nil,    46,   nil,    37,
   nil,   nil,   nil,    38,    36,   nil,    44,    45,    35,   nil,
    11,    43,   nil,    46,   nil,    37,   nil,   nil,   nil,    38,
    36,   nil,    44,    45,    35,   nil,    11,    43,   nil,    46,
   nil,    37,   nil,   nil,   nil,    38,    36,   nil,    44,    45,
    35,   nil,    11,    43,   nil,    46,   nil,    37,   nil,   nil,
   nil,    38,    36,   nil,    44,    45,    35,   nil,    11,    43,
   nil,    46,   nil,    37,   nil,   nil,   nil,    38,    36,   nil,
    44,    45,    35,   nil,    11,    43,   nil,    46,   nil,    37,
   nil,   nil,   nil,    38,    36,   nil,    44,    45,    35,   nil,
    11,    43,   nil,    46,   nil,    37,   nil,   nil,   nil,    38,
    36,   nil,    44,    45,    35,   nil,    11,    43,   nil,    46,
   nil,    37,   nil,   nil,   nil,    38,    36,   nil,    44,    45,
    35,   nil,    11,    43,   nil,    46,   nil,    37,   nil,   nil,
   nil,    38,    36,   nil,    44,    45,    35,   nil,    11,    43,
   nil,    46,   nil,    37,   nil,   nil,   nil,    38,    36,   nil,
    44,    45,    35,   nil,    11,    43,   nil,    46,   nil,    37,
   nil,   nil,   nil,    38,    36,   nil,    44,    45,   nil,   nil,
    11,    43,   nil,    46,   nil,   nil,    75,   nil,   nil,   nil,
    36,    57,    58,    59,    55,    56,    66,    65,    67,    68,
    69,    70,   nil,    60,    61,    64,   nil,    63,    62,    77,
    76,   nil,    57,    58,    59,    55,    56,    66,    65,    67,
    68,    69,    70,   nil,    60,    61,    64,   104,    63,    62,
    57,    58,    59,    55,    56,    66,    65,    67,    68,    69,
    70,   nil,    60,    61,    64,   nil,    63,    62,   110,   nil,
    57,    58,    59,    55,    56,    66,    65,    67,    68,    69,
    70,   nil,    60,    61,    64,   nil,    63,    62,   103,   nil,
    57,    58,    59,    55,    56,    66,    65,    67,    68,    69,
    70,   nil,    60,    61,    64,   nil,    63,    62,    57,    58,
    59,    55,    56,    66,    65,    67,    68,    69,    70,   nil,
    60,    61,    64,   nil,    63,    62,    57,    58,    59,    55,
    56,    66,    65,    67,    68,    69,    70,   nil,    60,    61,
    64,   nil,    63,    62,    57,    58,    59,    55,    56,    66,
    65,    67,    68,    69,    70,   nil,    60,    61,    64,    57,
    58,    59,    55,    56,    66,    65,    67,    68,    69,    70,
   nil,    60,    61,    64,    57,    58,    59,    55,    56,    66,
    65,    67,    68,    69,    70,   nil,    60,    61,    64,    20,
    21,    11,    20,    21,    11,   nil,   nil,     3,   nil,    23,
     3,    22,    23,   nil,    22,    20,    21,    11,    20,    21,
    11,   nil,   nil,     3,   nil,    23,     3,    22,    23,   nil,
    22,    20,    21,    11,   nil,   nil,   nil,   nil,   nil,     3,
   nil,    23,   nil,    22,    57,    58,    59,    55,    56,    66,
    65,    67,    68,    69,    70,   nil,    60,    20,    21,    11,
    20,    21,    11,   nil,   nil,     3,   nil,    23,     3,    22,
    23,   nil,    22,    57,    58,    59,    55,    56,    66,    65,
    67,    68,    69,    70,    57,    58,    59,    55,    56,    66,
    65,    67,    68,    69,    70,    57,    58,    59,    55,    56,
    66,    65,    67,    68,   -57,   -57,    57,    58,    59,    55,
    56,    66,    65,    67,    68,   -57,   -57,    57,    58,    59,
    55,    56,   -57,   -57,   -57,   -57,    57,    58,    59,    55,
    56,   -57,   -57,   -57,   -57,    57,    58,    59,    55,    56,
   -57,   -57,   -57,   -57,    57,    58,    59,    55,    56,   -57,
   -57,   -57,   -57 ]

racc_action_check = [
   105,    96,    50,    96,   111,   106,    97,     5,    29,     6,
    49,     5,    72,    72,    72,    72,    72,    72,    72,    72,
    72,    72,    72,    19,    72,    72,    72,    20,    72,    72,
     3,    80,    80,    80,     7,     5,     5,    50,     4,   105,
    96,   111,   106,    97,     6,    72,     1,    51,     3,     3,
     3,    26,    69,     0,     3,     3,     3,   nil,     3,    69,
     3,   nil,   nil,    69,   nil,   nil,    69,    69,    23,   nil,
    69,    69,   nil,    69,   nil,    23,    81,    81,    81,    23,
    69,   nil,    23,    23,    78,   nil,    23,    23,   nil,    23,
   nil,    78,   nil,   nil,   nil,    78,    23,   nil,    78,    78,
    77,   nil,    78,    78,   nil,    78,   nil,    77,   nil,   nil,
   nil,    77,    78,   nil,    77,    77,    21,   nil,    77,    77,
   nil,    77,   nil,    21,   nil,   nil,   nil,    21,    77,   nil,
    21,    21,    70,   nil,    21,    21,   nil,    21,   nil,    70,
   nil,   nil,   nil,    70,    21,   nil,    70,    70,    31,   nil,
    70,    70,   nil,    70,   nil,    31,   nil,   nil,   nil,    31,
    70,   nil,    31,    31,    22,   nil,    31,    31,   nil,    31,
   nil,    22,   nil,   nil,   nil,    22,    31,   nil,    22,    22,
    62,   nil,    22,    22,   nil,    22,   nil,    62,   nil,   nil,
   nil,    62,    22,   nil,    62,    62,    36,   nil,    62,    62,
   nil,    62,   nil,    36,   nil,   nil,   nil,    36,    62,   nil,
    36,    36,    37,   nil,    36,    36,   nil,    36,   nil,    37,
   nil,   nil,   nil,    37,    36,   nil,    37,    37,    38,   nil,
    37,    37,   nil,    37,   nil,    38,   nil,   nil,   nil,    38,
    37,   nil,    38,    38,    68,   nil,    38,    38,   nil,    38,
   nil,    68,   nil,   nil,   nil,    68,    38,   nil,    68,    68,
    67,   nil,    68,    68,   nil,    68,   nil,    67,   nil,   nil,
   nil,    67,    68,   nil,    67,    67,    66,   nil,    67,    67,
   nil,    67,   nil,    66,   nil,   nil,   nil,    66,    67,   nil,
    66,    66,   104,   nil,    66,    66,   nil,    66,   nil,   104,
   nil,   nil,   nil,   104,    66,   nil,   104,   104,    65,   nil,
   104,   104,   nil,   104,   nil,    65,   nil,   nil,   nil,    65,
   104,   nil,    65,    65,    63,   nil,    65,    65,   nil,    65,
   nil,    63,   nil,   nil,   nil,    63,    65,   nil,    63,    63,
    55,   nil,    63,    63,   nil,    63,   nil,    55,   nil,   nil,
   nil,    55,    63,   nil,    55,    55,    56,   nil,    55,    55,
   nil,    55,   nil,    56,   nil,   nil,   nil,    56,    55,   nil,
    56,    56,    57,   nil,    56,    56,   nil,    56,   nil,    57,
   nil,   nil,   nil,    57,    56,   nil,    57,    57,    58,   nil,
    57,    57,   nil,    57,   nil,    58,   nil,   nil,   nil,    58,
    57,   nil,    58,    58,    59,   nil,    58,    58,   nil,    58,
   nil,    59,   nil,   nil,   nil,    59,    58,   nil,    59,    59,
    60,   nil,    59,    59,   nil,    59,   nil,    60,   nil,   nil,
   nil,    60,    59,   nil,    60,    60,    61,   nil,    60,    60,
   nil,    60,   nil,    61,   nil,   nil,   nil,    61,    60,   nil,
    61,    61,    35,   nil,    61,    61,   nil,    61,   nil,    35,
   nil,   nil,   nil,    35,    61,   nil,    35,    35,   nil,   nil,
    35,    35,   nil,    35,   nil,   nil,    47,   nil,   nil,   nil,
    35,    47,    47,    47,    47,    47,    47,    47,    47,    47,
    47,    47,   nil,    47,    47,    47,   nil,    47,    47,    48,
    48,   nil,    48,    48,    48,    48,    48,    48,    48,    48,
    48,    48,    48,   nil,    48,    48,    48,    99,    48,    48,
    99,    99,    99,    99,    99,    99,    99,    99,    99,    99,
    99,   nil,    99,    99,    99,   nil,    99,    99,   107,   nil,
   107,   107,   107,   107,   107,   107,   107,   107,   107,   107,
   107,   nil,   107,   107,   107,   nil,   107,   107,    98,   nil,
    98,    98,    98,    98,    98,    98,    98,    98,    98,    98,
    98,   nil,    98,    98,    98,   nil,    98,    98,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,   nil,
    54,    54,    54,   nil,    54,    54,    33,    33,    33,    33,
    33,    33,    33,    33,    33,    33,    33,   nil,    33,    33,
    33,   nil,    33,    33,    74,    74,    74,    74,    74,    74,
    74,    74,    74,    74,    74,   nil,    74,    74,    74,    87,
    87,    87,    87,    87,    87,    87,    87,    87,    87,    87,
   nil,    87,    87,    87,    88,    88,    88,    88,    88,    88,
    88,    88,    88,    88,    88,   nil,    88,    88,    88,    75,
    75,    75,    76,    76,    76,   nil,   nil,    75,   nil,    75,
    76,    75,    76,   nil,    76,   110,   110,   110,    25,    25,
    25,   nil,   nil,   110,   nil,   110,    25,   110,    25,   nil,
    25,   103,   103,   103,   nil,   nil,   nil,   nil,   nil,   103,
   nil,   103,   nil,   103,    86,    86,    86,    86,    86,    86,
    86,    86,    86,    86,    86,   nil,    86,    28,    28,    28,
   101,   101,   101,   nil,   nil,    28,   nil,    28,   101,    28,
   101,   nil,   101,    73,    73,    73,    73,    73,    73,    73,
    73,    73,    73,    73,    85,    85,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    94,    94,    94,    94,    94,
    94,    94,    94,    94,    94,    94,    93,    93,    93,    93,
    93,    93,    93,    93,    93,    93,    93,    91,    91,    91,
    91,    91,    91,    91,    91,    91,    92,    92,    92,    92,
    92,    92,    92,    92,    92,    89,    89,    89,    89,    89,
    89,    89,    89,    89,    90,    90,    90,    90,    90,    90,
    90,    90,    90 ]

racc_action_pointer = [
    17,    46,   nil,    20,    38,     1,     7,     4,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6,
    -3,   104,   152,    56,   nil,   650,    21,   nil,   689,   -22,
   nil,   136,   nil,   588,   nil,   440,   184,   200,   216,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   473,   494,     6,
     0,    17,   nil,   nil,   570,   328,   344,   360,   376,   392,
   408,   424,   168,   312,   nil,   296,   264,   248,   232,    40,
   120,   nil,     4,   725,   606,   631,   634,    88,    72,   nil,
    23,    68,   nil,   nil,   nil,   736,   696,   621,   636,   787,
   796,   769,   778,   758,   747,   nil,    -1,     4,   552,   512,
   nil,   692,   nil,   663,   280,    -2,     3,   532,   nil,   nil,
   647,     2,   nil ]

racc_action_default = [
   -57,   -57,    -1,   -57,   -57,   -57,   -57,   -57,    -6,    -7,
    -8,   -11,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -57,
   -57,   -57,   -57,   -57,   113,   -57,   -57,    -3,   -57,    -5,
   -10,   -57,   -21,   -22,   -28,   -57,   -57,   -57,   -57,   -49,
   -50,   -51,   -52,   -53,   -54,   -55,   -56,   -57,   -57,   -52,
   -57,    -4,   -12,    -9,   -20,   -57,   -57,   -57,   -57,   -57,
   -57,   -57,   -57,   -57,   -42,   -57,   -57,   -57,   -57,   -57,
   -57,   -34,   -57,   -38,   -41,   -57,   -57,   -57,   -57,    -2,
   -29,   -30,   -31,   -32,   -33,   -36,   -37,   -39,   -40,   -43,
   -44,   -45,   -46,   -47,   -48,   -35,   -57,   -57,   -57,   -57,
   -23,   -57,   -25,   -57,   -57,   -57,   -57,   -57,   -24,   -26,
   -57,   -57,   -27 ]

racc_goto_table = [
     6,    33,    47,    48,    19,     7,     5,    26,    30,    29,
     2,    54,     1,   nil,   nil,    71,    72,    73,    74,   nil,
   nil,    32,    50,   nil,    49,    52,    19,    30,    51,    19,
    53,   nil,   nil,   nil,   nil,    80,    81,    82,    83,    84,
    85,    86,    87,    88,   nil,    89,    90,    91,    92,    93,
    94,   nil,    53,   nil,   nil,   nil,   nil,    98,    99,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    96,    97,   nil,   nil,    19,    19,   nil,   nil,
   nil,   nil,   nil,   nil,   107,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   105,   nil,
   106,   nil,    19,   nil,    19,   nil,   nil,   111,   nil,   nil,
   nil,    19 ]

racc_goto_check = [
     4,    14,    14,    14,     7,     5,     3,     5,     7,     6,
     2,    14,     1,   nil,   nil,    14,    14,    14,    14,   nil,
   nil,     7,     4,   nil,     7,     4,     7,     7,     6,     7,
     7,   nil,   nil,   nil,   nil,    14,    14,    14,    14,    14,
    14,    14,    14,    14,   nil,    14,    14,    14,    14,    14,
    14,   nil,     7,   nil,   nil,   nil,   nil,    14,    14,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     4,     4,   nil,   nil,     7,     7,   nil,   nil,
   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,   nil,
     4,   nil,     7,   nil,     7,   nil,   nil,     4,   nil,   nil,
   nil,     7 ]

racc_goto_pointer = [
   nil,    12,    10,     3,    -3,     2,     2,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   -20,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    18,   nil,   nil,   nil,   nil,    42,    12,    13,
    14,    15,    16,    17,   nil,    34,    39,    40,    41 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 43, :_reduce_1,
  5, 44, :_reduce_2,
  3, 44, :_reduce_3,
  3, 45, :_reduce_none,
  2, 45, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  1, 47, :_reduce_none,
  2, 48, :_reduce_none,
  1, 48, :_reduce_none,
  1, 49, :_reduce_none,
  3, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_15,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  1, 46, :_reduce_none,
  3, 50, :_reduce_none,
  2, 51, :_reduce_none,
  2, 52, :_reduce_22,
  5, 53, :_reduce_none,
  7, 53, :_reduce_none,
  5, 54, :_reduce_none,
  7, 55, :_reduce_none,
  9, 55, :_reduce_none,
  1, 56, :_reduce_28,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  2, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  2, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  2, 56, :_reduce_none,
  2, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  3, 56, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  1, 57, :_reduce_51,
  1, 57, :_reduce_none,
  1, 58, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 60, :_reduce_56 ]

racc_reduce_n = 57

racc_shift_n = 113

racc_token_table = {
  false => 0,
  :error => 1,
  :SEMI_COLON => 2,
  :INTERROGATION_MARK => 3,
  :COLON => 4,
  :DOUBLE_DOT => 5,
  :PIPE => 6,
  :MINUS_UNARY => 7,
  :MULTIPLY => 8,
  :DIVISION => 9,
  :PERCENT => 10,
  :PLUS => 11,
  :MINUS => 12,
  :LESS_EQUAL => 13,
  :LESS => 14,
  :MORE => 15,
  :MORE_EQUAL => 16,
  :EQUAL => 17,
  :INEQUAL => 18,
  :NOT => 19,
  :AND => 20,
  :OR => 21,
  :APOSTROPHE => 22,
  :DOLLAR => 23,
  :VIRGUILE => 24,
  :AMPERSAND => 25,
  :TRUE => 26,
  :FALSE => 27,
  :READ => 28,
  :WRITE => 29,
  :IDENTIFIER => 30,
  :NUMBER => 31,
  :EMPTY_CANVAS => 32,
  :CANVAS => 33,
  :EXCLAMATION_MARK => 34,
  :AT => 35,
  :LCURLY => 36,
  :RCURLY => 37,
  :LBRACKET => 38,
  :RBRACKET => 39,
  :LPARENTHESIS => 40,
  :RPARENTHESIS => 41 }

racc_nt_base = 42

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEMI_COLON",
  "INTERROGATION_MARK",
  "COLON",
  "DOUBLE_DOT",
  "PIPE",
  "MINUS_UNARY",
  "MULTIPLY",
  "DIVISION",
  "PERCENT",
  "PLUS",
  "MINUS",
  "LESS_EQUAL",
  "LESS",
  "MORE",
  "MORE_EQUAL",
  "EQUAL",
  "INEQUAL",
  "NOT",
  "AND",
  "OR",
  "APOSTROPHE",
  "DOLLAR",
  "VIRGUILE",
  "AMPERSAND",
  "TRUE",
  "FALSE",
  "READ",
  "WRITE",
  "IDENTIFIER",
  "NUMBER",
  "EMPTY_CANVAS",
  "CANVAS",
  "EXCLAMATION_MARK",
  "AT",
  "LCURLY",
  "RCURLY",
  "LBRACKET",
  "RBRACKET",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "$start",
  "S",
  "ESTRUCT",
  "DEC",
  "INSTR",
  "TIPO",
  "LISTIDENT",
  "VARIABLE",
  "ASSIGN",
  "IN",
  "OUT",
  "CONDIC",
  "ITERIND",
  "ITERDET",
  "EXPR",
  "IDENTIF",
  "NUM",
  "BOOL",
  "LIEN" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 37)
  def _reduce_1(val, _values, result)
     result = S.new(val[0]); result.print_tree
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 42)
  def _reduce_2(val, _values, result)
     result = ESTRUCT.new(val[1],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 43)
  def _reduce_3(val, _values, result)
     result = ESTRUCT.new(nil,val[1]) 
    result
  end
.,.,

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'Parser.y', 75)
  def _reduce_15(val, _values, result)
     result = INSTR.new(nil,val[0]) 
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'Parser.y', 94)
  def _reduce_22(val, _values, result)
     result = WRITE.new(val[1]) 
    result
  end
.,.,

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

module_eval(<<'.,.,', 'Parser.y', 116)
  def _reduce_28(val, _values, result)
    result = EXPR_IDENT.new(val[0])
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

module_eval(<<'.,.,', 'Parser.y', 142)
  def _reduce_51(val, _values, result)
    result = IDENTIF.new(val[0])
    result
  end
.,.,

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

module_eval(<<'.,.,', 'Parser.y', 156)
  def _reduce_56(val, _values, result)
     result = LIEN.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
